create or replace view AVG_DAY_BY_DAY_CONSUMPTION(
	DATE,
	WAREHOUSE_NAME,
	CREDITS_USED_COMPUTE,
	RNK,
	AVERAGE,
	STDV
) as
with ss as(
    SELECT 
    DATE(START_TIME) as DATE
    --    DATE(START_TIME) || ' - ' || LPAD(HOUR(START_TIME), 2, '0') as DATE
    ,WAREHOUSE_NAME
    ,sum(CREDITS_USED_COMPUTE) as CREDITS_USED_COMPUTE
    ,dense_rank() OVER (PARTITION BY DATE ORDER BY sum(CREDITS_USED_COMPUTE) desc) as rnk
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
    WHERE START_TIME >= DATEADD(DAY, -120, CURRENT_TIMESTAMP())
    AND WAREHOUSE_ID > 0  // Skip pseudo-VWs such as "CLOUD_SERVICES_ONLY"
    GROUP BY 1,2
    -- QUALIFY rnk <= 5
    ORDER BY 1, rnk
)
select *, avg(CREDITS_USED_COMPUTE) over(partition by DATE) as AVERAGE, stddev(CREDITS_USED_COMPUTE) over(partition by DATE) STDV
from ss
;