create or replace view WAREHOUSES_VW(
	WH_NAME,
	WH_SIZE,
	AUTO_SUSPEND,
	NODES
) as
WITH sizes AS (
 SELECT 'X-SMALL' AS WAREHOUSE_SIZE, 1 AS NODES
   UNION ALL
   SELECT 'SMALL' AS WAREHOUSE_SIZE, 2 AS NODES
   UNION ALL
   SELECT 'MEDIUM' AS WAREHOUSE_SIZE, 4 AS NODES
   UNION ALL
   SELECT 'LARGE' AS WAREHOUSE_SIZE, 8 AS NODES
   UNION ALL
   SELECT 'X-LARGE' AS WAREHOUSE_SIZE, 16 AS NODES
   UNION ALL
   SELECT '2X-LARGE' AS WAREHOUSE_SIZE, 32 AS NODES
   UNION ALL
   SELECT '3X-LARGE' AS WAREHOUSE_SIZE, 64 AS NODES
   UNION ALL
   SELECT '4X-LARGE' AS WAREHOUSE_SIZE, 128 AS NODES
)
select "name" as wh_name, "size" as wh_size, "auto_suspend" as auto_suspend, NODES from table(result_scan(last_query_id())) q
LEFT JOIN sizes s ON s.WAREHOUSE_SIZE = UPPER(q.$4)
ORDER BY nodes;


