CREATE OR REPLACE PROCEDURE MONITORING.MONITORING_SCHEMA.AVG_DAY_BY_DAY_CONSUMPTION()
RETURNS TABLE ("DATE" DATE, "WAREHOUSE_NAME" VARCHAR, "CREDITS_USED_COMPUTE" FLOAT, "RNK" NUMBER(38,0), "AVERAGE" FLOAT, "STDV" FLOAT)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
 LET results RESULTSET := (
    with ss as(
        SELECT 
        DATE(START_TIME) as DATE
        ,WAREHOUSE_NAME
        ,CAST(sum(CREDITS_USED_COMPUTE) as float) as CREDITS_USED_COMPUTE
        ,dense_rank() OVER (PARTITION BY DATE ORDER BY sum(CREDITS_USED_COMPUTE) desc) as rnk
        FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
        WHERE START_TIME >= DATEADD(DAY, -120, CURRENT_TIMESTAMP())
        AND WAREHOUSE_ID > 0  // Skip pseudo-VWs such as "CLOUD_SERVICES_ONLY"
        GROUP BY 1,2
    )
    select * , CAST(avg(CREDITS_USED_COMPUTE) over(partition by DATE) as float) as AVERAGE, CAST(stddev(CREDITS_USED_COMPUTE) over(partition by DATE) as float) STDV
    from ss
    );

    RETURN TABLE(results);
END;
';