CREATE OR REPLACE PROCEDURE MONITORING.MONITORING_SCHEMA.DAILY_PEAKS1()
RETURNS TABLE ("DATE" DATE, "YEAR" NUMBER(38,0), "MONTH" NUMBER(38,0), "WEEK" NUMBER(38,0), "DAY" NUMBER(38,0), "WAREHOUSE_NAME" VARCHAR, "CREDITS_USED" FLOAT)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
 LET results RESULTSET := (
         SELECT 
               DATE(START_TIME) as  DATE
            , YEAR(START_TIME)::int as YEAR
            , MONTH(START_TIME)::int as MONTH
            , LPAD(WEEK(START_TIME),2 , ''0'')::int as WEEK
            , LPAD(DAY(START_TIME),2 , ''0'')::int as DAY
            , WAREHOUSE_NAME
            , sum(CREDITS_USED_COMPUTE)::float as CREDITS_USED_COMPUTE
             FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
         GROUP BY ALL
    );

    RETURN TABLE(results);
END;
';