CREATE OR REPLACE PROCEDURE MONITORING.MONITORING_SCHEMA.DAILY_PEAKS()
RETURNS TABLE ("DATE" DATE, "YEAR" NUMBER(38,0), "MONTH" NUMBER(38,0), "WEEK" NUMBER(38,0), "DAY" NUMBER(38,0), "HOUR" NUMBER(38,0), "WAREHOUSE_NAME" VARCHAR, "1" FLOAT, "2" FLOAT, "3" FLOAT, "4" FLOAT, "5" FLOAT, "6" FLOAT, "7" FLOAT, "8" FLOAT, "9" FLOAT, "10" FLOAT, "11" FLOAT, "12" FLOAT, "13" FLOAT, "14" FLOAT, "15" FLOAT, "16" FLOAT, "17" FLOAT, "18" FLOAT, "19" FLOAT, "20" FLOAT, "21" FLOAT, "22" FLOAT, "23" FLOAT, "24" FLOAT, "25" FLOAT, "26" FLOAT, "27" FLOAT, "28" FLOAT, "29" FLOAT, "30" FLOAT, "31" FLOAT)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
 LET results RESULTSET := (
WITH data as(
         SELECT 
               DATE(START_TIME) as  DATE
            , YEAR(START_TIME)::int as YEAR
            , MONTH(START_TIME)::int as MONTH
            , LPAD(WEEK(START_TIME),2 , ''0'')::int as WEEK
            , LPAD(DAY(START_TIME),2 , ''0'')::int as DAY
            , LPAD(HOUR(START_TIME), 2, ''0'')::int as HOUR
            , WAREHOUSE_NAME
            , sum(CREDITS_USED_COMPUTE)::float as CREDITS_USED_COMPUTE
             FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
         GROUP BY 1,2,3,4,5,6,7
         ORDER BY 1,2,3,4,5
     )
     select *
     from data
         PIVOT(sum(CREDITS_USED_COMPUTE) FOR DAY in(01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12, 13, 14, 15
         , 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31)) as d
    );

    RETURN TABLE(results);
END;
';