CREATE OR REPLACE PROCEDURE MONITORING.MONITORING_SCHEMA.SEVEN_DAY_AVERAGE_TREND()
RETURNS TABLE ("START_DATE" DATE, "WAREHOUSE_NAME" VARCHAR, "CREDITS_USED_DATE_WH" FLOAT, "CREDITS_USED_7_DAY_AVG" FLOAT, "PCT_OVER_TO_7_DAY_AVERAGE" FLOAT)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
 LET results RESULTSET := (
        WITH CTE_DATE_WH AS(
           SELECT TO_DATE(START_TIME) AS START_DATE
                 ,WAREHOUSE_NAME
                 ,SUM(CREDITS_USED) AS CREDITS_USED_DATE_WH
             FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
            GROUP BY START_DATE
                    ,WAREHOUSE_NAME
         )
         SELECT START_DATE::DATE as START_DATE
               ,WAREHOUSE_NAME
               ,CREDITS_USED_DATE_WH::float as CREDITS_USED_DATE_WH
               ,CAST(AVG(CREDITS_USED_DATE_WH) OVER (PARTITION BY WAREHOUSE_NAME ORDER BY START_DATE ROWS 7 PRECEDING) as float) AS CREDITS_USED_7_DAY_AVG
               ,100.0*((CREDITS_USED_DATE_WH / CREDITS_USED_7_DAY_AVG) - 1)::float AS PCT_OVER_TO_7_DAY_AVERAGE
           FROM CTE_DATE_WH
    );

    RETURN TABLE(results);
END;
';