CREATE OR REPLACE PROCEDURE MONITORING.MONITORING_SCHEMA.WH_MONTHLY_CONSUMPTION_VW()
RETURNS TABLE ("YEAR_MONTH" VARCHAR, "NAME" VARCHAR, "SERVICE_TYPE" VARCHAR, "SERVICE_GROUP" VARCHAR, "CREDITS_USED_COMPUTE_SUM" FLOAT, "CREDITS_USED_CLOUD_SERVICES" FLOAT, "CREDITS_USED" FLOAT)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
 LET results RESULTSET := (
        SELECT YEAR(START_TIME) ||''-''|| LPAD(MONTH(START_TIME),2 , ''0'') as YEAR_MONTH
       , NAME
       , SERVICE_TYPE
       , case when SERVICE_TYPE = ''WAREHOUSE_METERING'' then ''WAREHOUSE_METERING'' else ''OTHER'' end as SERVICE_GROUP
       , cast(SUM(CREDITS_USED_COMPUTE) as float) AS CREDITS_USED_COMPUTE_SUM
       , cast(SUM(CREDITS_USED_CLOUD_SERVICES) as float) as CREDITS_USED_CLOUD_SERVICES
       , cast(SUM(CREDITS_USED) as float) as CREDITS_USED
    FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
    GROUP BY all
    );

    RETURN TABLE(results);
END;
';